# Site settings
title: Janelle Gatchalian
email: jbgatchalian@gmail.com
description: 'Janelle Gatchalian jbgatchalian at gmail.com'
baseurl: '/portfolio' # the subpath of your site, e.g. /blog/
url: "http://janelle-gatchalian.github.io" # the base hostname & protocol for your site
copyright: '&copy; 2015-2016 Smart Material Theme'

# Build settings
markdown: kramdown

# Custom theme could be generated at: https://getmdl.io/customize/index.html
material_theme: deep_purple-red

# Google Analytics account ID (UA-XXXXXXXX-X)

google-analytics-ua: UA-84475574-1
